### ISSUE TITLE
Validar os ids caso não tenha nada no banco nas tabelas de rankis

### ISSUE THREAD

**Issue by FranciscoWallison** [rscodexx/ragpainel#2]
Ao entrar na tela de rankis retorna erro de validação de tabela.

**Comment by rscodexx** [comment]
Corrigido [8873095b420d16f748a8bb76b112dc6e1edce309](https://github.com/rscodexx/ragpainel/commit/8873095b420d16f748a8bb76b112dc6e1edce309)

Obrigado pelo reporte.
